Add validation to the registration page according to F1.1.1-F1.1.4
unseeing-hawk/calorie_tracker pull request #39
Opened 2023-11-16 02:43 UTC by famv2000

Closes #29

2023-11-22 17:19 UTC, AlexHeiden commented on client-calorie-tracker/src/main/resources/static/resources/js/signup.js
> +function setAnimationError(el) {
Ошибки в валидации:

1) Положительные числа от 0 до 1 в поле weight почему-то считаются невалидными

2) В поле weight можно вставить бесконечно большое число, что противоречит диапазону значений float

3) Логин здесь не может содержать ";" и прочие символы, о которых ничего не говорится в спецификации

2023-11-24 14:24 UTC, AlexHeiden requested changes

2023-11-24 14:24 UTC, AlexHeiden commented on client-calorie-tracker/src/main/resources/static/resources/js/signup.js
> +function setAnimationError(el) {
Ошибки при валидации:

1) Опечатка в слове "weight", когда пишу некорректный вес в соответствующем поле. Просто поменяй "weigth" на "weight"

2) Поле name автоматически преобразует первые буквы имени в заглавные. Однако я написал имя с маленькой буквы в текстовом редакторе, скопировал и вставил в <name>. Программа не нашла ошибок в таком имени. Нужно точно проверять, что в каждой части имени первая буква заглавная, как по спецификации.

2023-11-24 14:45 UTC, AlexHeiden commented on client-calorie-tracker/src/main/resources/static/resources/js/signup.js
> +function setAnimationError(el) {
3. Программа позволяет вводить нулевое значение в поле weight

2023-11-25 13:26 UTC, famv2000 commented on client-calorie-tracker/src/main/resources/static/resources/js/signup.js
> +function setAnimationError(el) {
Исправлено.

2023-11-27 16:26 UTC, merged