nhan/add validation to the settings page
unseeing-hawk/calorie_tracker pull request #48
Opened 2023-11-24 02:39 UTC by famv2000

Closes #31

2023-11-24 14:46 UTC, AlexHeiden requested changes

2023-11-24 14:46 UTC, AlexHeiden commented on client-calorie-tracker/src/main/resources/static/resources/js/settings.js
> +function setAnimationError(el) {
Смотри замечания PR валидации регистрации

2023-11-25 13:31 UTC, famv2000 commented on client-calorie-tracker/src/main/resources/static/resources/js/settings.js
> +function setAnimationError(el) {
Исправлено.

2023-11-27 19:26 UTC, AlexHeiden approved these changes

2023-11-28 07:37 UTC, merged