p.pankova/get user products #54
unseeing-hawk/calorie_tracker pull request #81
Opened 2023-12-09 14:40 UTC by unseeing-hawk

Добавлена функциональность для кнопки "Мои продукты"

2023-12-09 15:21 UTC, AlexHeiden requested changes

2023-12-09 15:21 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
> +    @GetMapping("/userProducts")
У нас нет эндпоинта "/userProducts" по OpenApi. Если хочешь разделить функционал, то лучше сделать 2 различные функции внутри сервиса, а здесь оставить единый эндпоинт GET /products

2023-12-09 15:21 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
> +    public List<Product> getUserProducts(@Valid ProductGetDTO productGetDTO) {
1) Не по OpenApi возвращаешь список ProductGetDTO вместо ProductDTO. В итоге возвращаешь внутри него весь объект пользователя, что достаточно громоздко. Я специально предусмотрел в ProductDTO, чтобы там был просто логин пользователя, а не весь объект

2) Учитывая, что ты не используешь здесь валидационные аннотации, не понимаю, зачем писать @Valid

2023-12-09 15:21 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
> +    public List<Product> getUserProducts(@RequestBody ProductGetDTO productGetDTO) {
По OpenApi у нас здесь не RequestBody, а несколько PathVariable. Для них можно даже дефолтное значение назначить, если пользователь их не ввел.

Общее замечание по всему коду. Очень много отличий от OpenApi. При разработке в первую очередь ориентируйся на нее, там вся инфа о входах, выходах и исключениях, регулярно все обновляю. Если ты с чем-то несогласна в OpenApi, то напиши, можем обсудить

2023-12-09 15:21 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
> +        User user = userDAO.findByLogin(productGetDTO.getUserLogin());
Рискуем вывалиться с NullPointerException. Притом на всех параметрах, тк они не проверяются

2023-12-09 15:21 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
> +    public List<Product> getUserProducts(@RequestBody ProductGetDTO productGetDTO) {
А еще для каждой PathVariable можно задать разные валидационные аннотации на уровне контроллера

2023-12-09 15:21 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
> +        if (productGetDTO.getLimit() <= 0)
Для этого хватило бы одной валидационной аннотации @Min(1). И кода сразу меньше станет

2023-12-09 15:21 UTC, AlexHeiden commented on client-calorie-tracker/src/main/resources/static/resources/css/add_product.css
> +    margin-bottom: 40px;
Ао, а почему отображаются изменения Ньяна при сравнении с develop? Если замерджим, у него ничего не сломается на фронте?

2023-12-09 15:21 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
> +        Pageable pageable = PageRequest.of(productGetDTO.getOffset(), productGetDTO.getLimit());
Пользователю здесь сейчас могут вывестись его удаленные продукты (где isActive = false).  Нужно это учитывать тоже

2023-12-10 08:51 UTC, unseeing-hawk commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
> +    @GetMapping("/userProducts")
в смысле "хочу разделить функционал"?) это и есть две разных логики. 

У нас две кнопки, делающих две разные вещи - возвращение продуктов пользователя и Поиск по Двум бд. Одно дело реализовывать запрос простого поиска, где от доп параметров меняется фильтрация и в целом логика поведения предсказуема. Ты предлагаешь мне написать так, что от одного параметра будет меняться логика работы. Мне кажется это каким-то неправильным.

2023-12-10 10:34 UTC, AlexHeiden requested changes

2023-12-10 10:34 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
> +    @GetMapping("/userProducts")
Давай он тогда будет /user-products. В ссылках стараются избегать camel case для читабельности

2023-12-10 10:34 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/rest/controller/ProductRestController.java
> +                                                @Min(value = 1, message = "Limit should not be less than 1")
В message по умолчанию пишется все с маленькой буквы и без упоминания валидированного поля. В данном случае правильно "must not be less than 1". В остальных сообщениях так же

2023-12-10 10:34 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
> +    public List<ProductPostDTO> getUserProducts(@Valid int limit,
В возвращаемом списке не хватает id продукта. Этот список также возвращается, когда пользователь хочет изменить продукты. И без возвращаемого id это будет очень сложно

2023-12-10 10:34 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
> +            violationList.add(new Violation("getUserProducts.productGetDTO.userLogin",
В violation неправильный путь. Должен быть "getUserProducts.userLogin"

2023-12-10 10:34 UTC, AlexHeiden commented on rest-calorie-tracker/src/main/java/ru/unfatcrew/restcalorietracker/service/ProductService.java
> +            violationList.add(new Violation("getUserProducts.productGetDTO.userLogin",
Точнее "getUserProducts.user-login"

2023-12-11 18:22 UTC, AlexHeiden approved these changes

2023-12-11 20:41 UTC, merged